media:
  input: public/tumblr
  output: /tumblr

settings:
  content:
    merge: true

content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    subfolders: false
    filename:
      template: "{year}-{month}-{day}-{primary}.md"
      field: create
    view:
      fields: [title, pubDatetime, tags]
      primary: title
      sort: [pubDatetime, title]
      default:
        sort: pubDatetime
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDatetime
        label: Published
        type: date
        required: true
        options:
          time: true
      - name: description
        label: Description
        type: string
        required: true
        options:
          maxlength: 200
      - name: tags
        label: Tags
        type: string
        list: true
      - name: featured
        label: Featured
        type: boolean
      - name: draft
        label: Draft
        type: boolean
      - name: author
        label: Author
        type: string
        default: misoverstood
        hidden: true
      - name: timezone
        label: Timezone
        type: string
        default: America/Toronto
        hidden: true
      - name: body
        label: Body
        type: rich-text